 language: python
 python:
     - "2.7"

 sudo: false
 cache:
     directories:
         - "~/.platformio"

 install:
     - pip install -U platformio
     - wget https://lowpowerlab.github.io/MoteinoCore/Moteino1.6.1.zip -O /tmp/moteino.zip
     - unzip /tmp/moteino.zip -d /tmp/
     - mv /tmp/Moteino-1.6.1/variants/MoteinoMEGA/pins_arduino.h ~/.platformio/packages/framework-arduino-avr/variants/moteinomega

 script:
     - platformio run
